image: mcr.microsoft.com/dotnet/sdk:9.0

services:
  - name: docker:dind
    alias: docker
variables:
  DOCKER_HOST: tcp://docker:2375

stages:
    - build
    - test

build_web_app:
    stage: build
    script:
        - cd WebApplication
        - dotnet build
    only:
        - main

build_worker:
    stage: build
    script:
        - cd Worker
        - dotnet build
    only:
        - main

test_web_app:
    stage: test
    script:
        - cd WebApplication.Tests
        - dotnet test
    only:
        - main
