image: mcr.microsoft.com/dotnet/sdk:9.0

services:
  - name: docker:dind
    alias: docker
    command: ["--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  
stages:
  - build
  - test
  - binaries

build_web_app:
  stage: build
  script:
    - cd WebApplication
    - dotnet build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'main'

build_worker:
  stage: build
  script:
    - cd Worker
    - dotnet build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'main'

test_web_app:
  stage: test
  script:
    - cd WebApplication.Tests
    - dotnet test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'main'

test_worker_app:
    stage: test
    script:
        - cd Worker.Tests
        - dotnet test
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        - if: $CI_COMMIT_BRANCH == 'main'

worker_binaries:
    stage: binaries
    script:
        - cd Worker
        - dotnet restore
        - dotnet publish -c Release -r linux-x64 -p:PublishSingleFile=true -p:SelfContained=true
    artifacts:
      paths:
        - Worker/bin/Release/net*/linux-x64/publish/Worker

